spring.application.name=Caching_Application

server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/Cache
spring.datasource.username=root
spring.datasource.password=abhi2003#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#redis configuration
#spring.redis.host=localhost
#spring.redis.port=6379

#redis configuration using redis cloud
spring.data.redis.host=sienna-company-mass-59208.db.redis.io
spring.data.redis.port=13834
spring.data.redis.password=k2Gnh4uC5y7rU1ewyBJKeL1MTHKqolQF
